config/routes.rb
Rails.application.routes.draw do
  root to: "webfront#show", as: :root

  namespace :api, constraints: { format: :json } do
    resources :flows, only: [:show, :update]
    resources :executions, only: [:show, :update]
  end

  ##########################################
  get "/flows" => "flows#list"
  get "/flows/new" => "flows#new"
  post "/flows/create" => "flows#create"
  get "/flows/:identifier/edit" => "flows#edit"
  post "/flows/:identifier/update" => "flows#update"
  get "/flows/:identifier/delete" => "flows#delete"
  get "/flows/:identifier/copy" => "flows#copy"
  ##########################################
  get "/gallery" => "gallery#list"
  ##########################################
  get "/sign_in" => "account#sign_in_form"
  post "/do_sign_in" => "account#sign_in"
  get "/do_sign_out" => "account#sign_out"
  get "/myself" => "account#form"
  post "/myself/update" => "account#update"
  get "/account/:identifier/activate" => "account#activate"
  ##########################################
  get "/sign_up" => "account#sign_up_form"
  post "/do_sign_up" => "account#sign_up"
  ##########################################
  get "/" => "webfront#show"
  ##########################################
  get "/flows/:identifier/editor" => "editor#index"
  ##########################################
  get "/flows/:identifier/execute" => "executor#index"
  get "/f/:identifier" => "executor#index"
  get "/x/:identifier" => "executor#resume"
  get "/embed/:identifier" => "executor#index"
  ##########################################
  get "/media/:id/inline_image" => "media#inline_image"
end

app/models/flow.rb
class Flow < ApplicationRecord
  belongs_to :user
  has_many :executions

  def as_api_result
    {
      identifier: identifier,
      title: title,
      descriptor: descriptor,
    }
  end

  def copies
    Flow.where(copied_from: id)
  end

  def display_count
    executions.count
  end

  def under_execution_count
    executions.where(complete: false, started: true).count
  end

  def complete_executions
    executions.where(complete: true).count
  end
end

app/controllers/api/flows_controller.rb
class Api::FlowsController < ApiController
  before_action :user_from_header
  before_action :set_flow_by_identifier, only: [:show, :update]

  def show
    permission_service = ::Access::FlowPermissions.new(@flow, current_user).call
    return render json: {}, status: 401 unless permission_service.ok?

    flow_permissions = permission_service.get

    if flow_permissions[:can_edit]
      render json: @flow.as_api_result
    else
      render json: {}, status: 401
    end
  end

  def update
    permission_service = ::Access::FlowPermissions.new(@flow, current_user).call
    return render json: {}, status: 401 unless permission_service.ok?

    flow_permissions = permission_service.get

    if flow_permissions[:can_edit]
      descriptor = request.body.read

      service_result = ::Flowchart::Update.new(
        { 
          identifier: @flow.identifier,
          descriptor: descriptor,
        },
        current_user
      ).call

      if service_result.ok?
        ::FlowExecution::Invalidate.new(@flow.identifier).call

        render json: {}, status: 200
      else
        render json: {}, status: 500
      end
    else
      render json: {}, status: 401
    end
  end

  private

  def set_flow_by_identifier
    @flow = Flow.find_by(identifier: params[:id])
  end
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController
  before_action :location_info
  before_action :user_from_cookie
  before_action :redirect_if_not_in_session
  before_action :set_flow_by_identifier, only: [:edit, :update, :delete, :copy]

  def list
    add_crumb(nil, "flows")
    @flows = Flow.where(user_id: current_user.id)
  end

  def new
    add_crumb("/flows", "flows")
    add_crumb(nil, "new flow")
  end

  def edit
    add_crumb("/flows", "flows")
    add_crumb(nil, "editing flow")
  end

  def create
    service_result = ::Flowchart::Create.new(create_flow_params, current_user).call
    unless service_result.ok?
      redirect_to "/flows/new", notice: service_result.get
    else
      redirect_to "/flows"
    end
  end

  def update
    permission_service = ::Access::FlowPermissions.new(@flow, current_user).call
    return redirect_to "/401" unless permission_service.ok?

    flow_permissions = permission_service.get

    if flow_permissions[:can_edit]
      service_result = ::Flowchart::Update.new(create_flow_params, current_user).call
      unless service_result.ok?
        redirect_to "/flows/#{@flow.identifier}/edit", notice: service_result.get
      else
        redirect_to "/flows"
      end
    else
      redirect_to "/401"
    end
  end

  def copy
    permission_service = ::Access::FlowPermissions.new(@flow, current_user).call
    return redirect_to "/401" unless permission_service.ok?

    flow_permissions = permission_service.get

    if flow_permissions[:can_copy]
      service_result = ::Flowchart::Copy.new(create_flow_params, current_user).call
      unless service_result.ok?
        redirect_to "/gallery", notice: service_result.get
      else
        redirect_to "/flows"
      end
    else
      redirect_to "/401"
    end
  end

  def delete
    permission_service = ::Access::FlowPermissions.new(@flow, current_user).call
    return redirect_to "/401" unless permission_service.ok?

    flow_permissions = permission_service.get

    if flow_permissions[:can_delete]
      ::Flowchart::Delete.new(delete_flow_params, current_user).call
      redirect_to "/flows"
    else
      redirect_to "/401"
    end
  end

  private

  def set_flow_by_identifier
    @flow = Flow.find_by(identifier: params[:identifier])
  end

  def create_flow_params
    params.permit(:identifier, :picture, :title, :brief, :public, :copyable)
  end

  def delete_flow_params
    params.permit(:identifier)
  end
end

app/helpers/api/v1/flow_helper.rb
module Api::V1::FlowHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/views/flows/_form.html.erb
<%= form_with(url: form_url, method: :post, local: true, multipart: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, value: flow&.title %>

  <%= form.label :brief %>
  <%= form.text_field :brief, value: flow&.brief %>

  <%= form.label :picture %>
  <%= form.file_field :picture %>
  <div class="file" data-bind="picture">
    <% if flow&.picture %>
      <img src="/media/<%= flow.picture %>/inline_image" />
    <% end %>
    <button class="button">pick file</button>
    <span>no file selected</span>
  </div>

  <div class="label">Public?</div>
  <%= form.check_box :public, checked: flow&.public? %>
  <label for="public"></label>

  <div class="label">Copyable?</div>
  <%= form.check_box :copyable, checked: flow&.copyable? %>
  <label for="copyable"></label>

  <div class="toolbar">
    <%= form.submit flow.nil? ? "Create" : "Update", class:"button" %>
    <%= link_to "Cancel", flows_path, class: "button -stripped" %>
  </div>
<% end %>

app/views/flows/edit.html.erb
<div class="internal">
  <div class="container">
    <h1>Update flow</h1>
    <%= render partial: "flows/form", locals: { form_url: "/flows/#{@flow.identifier}/update", flow: @flow }%>
  </div>
</div>

app/views/flows/list.html.erb
<div class="internal">
  <div class="container">
    <h1>My flows</h1>
    <a href="<%= flows_new_path %>" class="button">
      <div>new flow</div>
    </a>
    <% if @flows.count.zero? %>
      <div class="list">No flows to list</div>
    <% else %>
      <div class="list">
        <% @flows.each do |flow| %>
          <%= render partial: "shared/flow", locals: {flow: flow, type: :collection} %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/flows/new.html.erb
<div class="internal">
  <div class="container">
    <h1>Create flow</h1>
    <%= render partial: "flows/form", locals: { form_url: flows_create_path, flow: @flow }%>
  </div>
</div>